import = ["~/.config/alacritty/dracula-theme.toml"]

[font]
size = 22

[font.normal]
family = "DepartureMono Nerd Font"

# Disable ⌘Q to prevent accidental exit
[[keyboard.bindings]]
action = "None"
key = "Q"
mods = "Command"

# Disable ⌘W to prevent accidental exit
[[keyboard.bindings]]
action = "None"
key = "W"
mods = "Command"

[window]
dynamic_title = false
title = "Terminal"

[window.padding]
x = 10
y = 10
