[aws]
symbol = "aws:"
disabled = true

[gcloud]
symbol = "gcloud:"
format = 'on [$symbol$project(\($region\))]($style) '

[buf]
symbol = ":"

[c]
symbol = "C:"

[conda]
symbol = "conda:"

[dart]
symbol = "dart:"

[directory]
read_only = "read-only"
truncate_to_repo = false
before_repo_root_style = "cyan dimmed"
repo_root_style = "cyan"

[docker_context]
symbol = "docker:"

[elixir]
symbol = "elixr:"

[elm]
symbol = "elm:"

[git_commit]
disabled = true

[git_state]
disabled = true

[git_branch]
disabled = false
symbol = "branch:"

[git_metrics]
disabled = true

[git_status]
disabled = true

[golang]
symbol = "go:"

[haskell]
symbol = "haskell:"

[hg_branch]
symbol = "branch:"

[java]
symbol = "java:"

[julia]
symbol = "julia:"

[lua]
symbol = "lua:"

[memory_usage]
symbol = "mem:"

[meson]
symbol = "meson:"

[nim]
symbol = "nim:"

[nix_shell]
symbol = "nix:"

[nodejs]
symbol = "nodejs:"

[package]
symbol = "package:"

[python]
symbol = "python:"

[rlang]
symbol = "R:"

[ruby]
symbol = "ruby:"

[rust]
symbol = "rust:"

[scala]
symbol = "scala:"

[spack]
symbol = "spack:"

[kubernetes]
symbol = "kube:"
disabled = false
